### ISSUE TITLE
Render developer profile

### ISSUE THREAD

**Issue by ReenExe** [SenseyePrototype/SenseyePrototype#102]
Exists sources:
 - Elasticsearch (external & internal profiles)
 - MySQL (now only internals)

What happen when external profile will expired?
Should store some data of external profile to MySQL - to external site link after expired?

**Comment by ReenExe** [comment]
require register buttons

**Comment by ReenExe** [comment]
https://php-and-symfony.matthiasnoback.nl/2014/05/inject-a-repository-instead-of-an-entity-manager/
```yaml
services:
    acme_customer.customer_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - Acme\CustomerBundle\Entity\Customer
```
